// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRDAua_voeh97kUcC_3QoWBIvsNeT9Os',
    appId: '1:24534879724:web:2d76a12f0c854191a344c9',
    messagingSenderId: '24534879724',
    projectId: 'geoportal-de-gestion',
    authDomain: 'geoportal-de-gestion.firebaseapp.com',
    storageBucket: 'geoportal-de-gestion.firebasestorage.app',
    measurementId: 'G-H0PCWJ96DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdrap7k73POLpen_OjFTPyrREem-riW8',
    appId: '1:24534879724:android:4be8117562c13b3aa344c9',
    messagingSenderId: '24534879724',
    projectId: 'geoportal-de-gestion',
    storageBucket: 'geoportal-de-gestion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuS7QP6n-u2-Uf7X94xPwiEU1hdG7Nsos',
    appId: '1:24534879724:ios:c9a4eb21c3dae594a344c9',
    messagingSenderId: '24534879724',
    projectId: 'geoportal-de-gestion',
    storageBucket: 'geoportal-de-gestion.firebasestorage.app',
    iosBundleId: 'com.geoportal.geoportalPredios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuS7QP6n-u2-Uf7X94xPwiEU1hdG7Nsos',
    appId: '1:24534879724:ios:c9a4eb21c3dae594a344c9',
    messagingSenderId: '24534879724',
    projectId: 'geoportal-de-gestion',
    storageBucket: 'geoportal-de-gestion.firebasestorage.app',
    iosBundleId: 'com.geoportal.geoportalPredios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnRDAua_voeh97kUcC_3QoWBIvsNeT9Os',
    appId: '1:24534879724:web:3e98df06fc880360a344c9',
    messagingSenderId: '24534879724',
    projectId: 'geoportal-de-gestion',
    authDomain: 'geoportal-de-gestion.firebaseapp.com',
    storageBucket: 'geoportal-de-gestion.firebasestorage.app',
    measurementId: 'G-MH4WB1XGMK',
  );
}
